---
http_interactions:
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&location=&service_area=&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Thu, 08 May 2014 04:27:53 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 5f708f5a-1977-48e1-9d56-a00fe4ff45e7
      X-Runtime:
      - '0.026060'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 08 May 2014 04:27:53 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&org_name=Custom%20Value&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Thu, 08 May 2014 05:13:59 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 0c8e30dd-48a7-49f9-8258-e1b2af23df60
      X-Runtime:
      - '0.036085'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 08 May 2014 05:13:59 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&org_name=Custom%20Value&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Thu, 08 May 2014 05:47:02 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 0a56f767-fbd9-4e1d-abb1-0576d8bf12e0
      X-Runtime:
      - '0.033164'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 08 May 2014 05:47:02 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&location=&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Thu, 08 May 2014 06:14:00 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - eba8aaa6-476d-4ed1-9f90-77dc77fff5b9
      X-Runtime:
      - '0.022410'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 08 May 2014 06:14:00 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&org_name=Custom%20Value&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Thu, 08 May 2014 06:20:11 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 07b81aea-4542-48a9-b00e-3dde3769f8c4
      X-Runtime:
      - '0.021500'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 08 May 2014 06:20:11 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&location=Custom%20Value&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Cache-Control:
      - no-cache
      Content-Type:
      - application/json
      Date:
      - Thu, 08 May 2014 06:32:22 GMT
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 9494c363-d42b-469d-8353-91c834c0bef3
      X-Runtime:
      - '0.045098'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '68'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"error":"bad request","description":"Invalid ZIP code or address."}'
    http_version: 
  recorded_at: Thu, 08 May 2014 06:32:22 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?api_token=<API_TOKEN>&keyword=asdfasg
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Type:
      - application/json
      Date:
      - Thu, 08 May 2014 06:32:23 GMT
      Etag:
      - '"d751713988987e9331980363e24189ce"'
      X-Current-Page:
      - '1'
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 414cccaf-9832-492d-a467-82a907ec5285
      X-Runtime:
      - '0.021916'
      X-Total-Count:
      - '0'
      X-Total-Pages:
      - '0'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '2'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: "[]"
    http_version: 
  recorded_at: Thu, 08 May 2014 06:32:23 GMT
- request:
    method: get
    uri: http://ohanapi.herokuapp.com/api/search?action=index&api_token=<API_TOKEN>&controller=organizations&keyword=asdfg&kind=Human%20Services&location=Custom%20Value&service_area=smc&utf8=%E2%9C%93
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/vnd.ohanapi-v1+json
      User-Agent:
      - Ohanakapa Ruby Gem 1.0.0
      X-Api-Token:
      - "<API_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Cache-Control:
      - no-cache
      Content-Type:
      - application/json
      Date:
      - Thu, 08 May 2014 06:53:48 GMT
      X-Rack-Cache:
      - miss
      X-Request-Id:
      - 8323f3e9-3aef-482c-9abb-06b963f95cdb
      X-Runtime:
      - '0.040378'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Content-Length:
      - '68'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"error":"bad request","description":"Invalid ZIP code or address."}'
    http_version: 
  recorded_at: Thu, 08 May 2014 06:53:48 GMT
recorded_with: VCR 2.8.0
